### ISSUE TITLE
No rainfall data when using ERA5 data

### ISSUE THREAD

**Issue by choingjoo** [amcz/hysplit_metdata#1]
Hi,
I tried to calculate hysplit backward trajectory using ERA5 meteo data which is converted by python code. 
The conversion from ERA5 to input file for hysplit and running the model were successful.
But there is NO RAINFALL (all zero) when ERA5 data was applied, compared to using GDAS data.
Please let me know why the rainfall data is not available and some tips.
Thank you.

YC.

**Comment by amcz** [comment]
Could you clarify whether you mean that the precipitation field was not available in the ERA5 or whether it was available but just 0.  If the later, then it is possible that the ERA5 just does not agree with GDAS with respect to precip unless you have other reasons to believe that the precip data is not being converted properly.

**Comment by choingjoo** [comment]
Sorry for unclear question. 
I suspected disagreement with GDAS  format. please find the attachment of two results (one from GDAS, another from ERA5). column 16 is rainfall fields.
[GDAS.txt](https://github.com/amcz/hysplit_metdata/files/3409116/GDAS.txt)
[ERA5.txt](https://github.com/amcz/hysplit_metdata/files/3409117/ERA5.txt)

When I checked the initial downloaded ERA5 data before conversion (ERA5_2010_Jul23.2dpl.all.T1.grib), there is the precipitation field (TPP1).
So, I think that the converted ERA5 (i.e. 20100723_T1.grib) also include the 'TPP1' field (but, I didn't check the variable because the file can not accessible using grib command).
Please find attached log file when I converted the ERA5 data.
[output.log](https://github.com/amcz/hysplit_metdata/files/3409100/output.log)
Please let me know if my question still remains unclear
Thank you.

YC

**Comment by amcz** [comment]
You can use the profile program to see what variables are in your ARL formatted file.
