### ISSUE TITLE
era52arl.cfg conversion for ssrd and slhf not written correctly

### ISSUE THREAD

**Issue by amcz** [amcz/hysplit_metdata#10]
ssrd and slhf should both have conversion factors (sfccnv) of -0.00028.
ssrd is being written as +0.00028 and slhf not being written at all.

**Comment by amcz** [comment]
Fixed

**Comment by majonm** [comment]
In Possible issues you mentioned that :
**''heat fluxes (LTHF, SHTF)
HYSPLIT convention is that upward heat flux is positive. ERA5 uses the opposite convention.
Make sure that a conversion factor is negative in the era52arl.cfg file.''**
which refer respectively to ''slhf'' and ''sshf'' in ERA5 but this **closed issue** mentions an additional one which is ''ssrd'' or DSWF according to the era52arl.cfg file and all these variables have a conversion factor of +0.00028.
So the question is : should we just change the sign of the heat flux variables (slhf and sshf only) or should we consider make it for ssrd (surface_solar_radiation_downwards) also ? 
Thanks in advance.
