### ISSUE TITLE
unit conversion prior to hysplit usage

### ISSUE THREAD

**Issue by acatalano16** [amcz/hysplit_metdata#5]
In the get_era5_cds.py script, your comments mention that some variables (pressure, geopotential) will need conversion to more standard units:

    sname['WWND'] = ["w", '135', '0.01','135.128','vertical_velocity', '2','8']   #units Pa/s. convert to hPa/s for HYSPLIT
    sname['RELH'] = ["r", '157', '1.0', '157.128','relative_humidity']    #units %
    sname['HGTS'] = ["z", '129', '0.102','129.128','geopotential','3','4']  #units m^2 / s^2. Divide by 9.8m/s^2 to get meters.
    #sname['SPHU']= "q"     #units kg / kg category 1, number 0. multiplier is 1   #specific humidity. redundant since have RELH

I don't know precisely what the sname dict values mean, but it seems like the third value is the conversion multiplier. I'm unclear based on your comments - is this conversion automatically done through your script + era52arl? If not, at what stage from .grib to .ARL should/can the user convert?

Thanks for your help.

**Comment by amcz** [comment]
Yes, the third value is the conversion multiplier. The comments simply document how that value was arrived at. Those values will go into the era52arl.cfg file which will tell the converter code how to conver to the units that HYSPLIT expects.
