### ISSUE TITLE
problem when downloading era5 data. 

### ISSUE THREAD

**Issue by Akhilauppala2056** [amcz/hysplit_metdata#7]
MissingSchema: Invalid URL '{api-url}/resources/reanalysis-era5-pressure-levels': No schema supplied. Perhaps you meant http://{api-url}/resources/reanalysis-era5-pressure-levels?
This is the error i am getting

**Comment by amcz** [comment]
Could you provide the command that you are using to get this error?

**Comment by Akhilauppala2056** [comment]
I used example_small_area.sh file. When I am running that, it is showing
such kind of error.

**Comment by amcz** [comment]
The following is what I get when I run the script. Do you get any of this?
Check that your .cdsapirc file in $HOME is correct possibly. 
It looks like it is not reading the URL correctly.
The first line should be the following.
**url: https://cds.climate.copernicus.eu/api/v2**


RETRIEVING  month 01 day 1
Retrieve for:  2017-01-01 00:00/01:00/02:00/03:00/04:00/05:00/06:00/07:00/08:00/09:00/10:00/11:00/12:00/13:00/14:00/15:00/16:00/17:00/18:00/19:00/20:00/21:00/22:00/23:00
RETRIEVING 3d plTEMP UWND VWND WWND RELH HGTS
Retrieve levels  ['1000', '975', '950', '925', '900', '875', '850', '825', '800', '775', '750', '700', '650', '600', '550', '500', '450', '400', '350', '300', '250', '225', '200', '175', '150', '125', '100', '70', '50', '30', '20', '10', '7', '5', '3', '2', '1']
2020-02-21 13:02:24,701 INFO Sending request to https://cds.climate.copernicus.eu/api/v2/resources/reanalysis-era5-pressure-levels
2020-02-21 13:02:25,103 INFO Request is completed
2020-02-21 13:02:25,103 INFO Downloading http://136.156.132.105/cache-compute-0000/cache/data5/adaptor.mars.internal-1582307784.506145-20220-39-87d0d2f8-890b-48f9-90a1-9fed78ebab9e.grib to ./ERA5_2017.Jan01.3dpl.grib (51.2M)

**Comment by amcz** [comment]
You can also run python interactively and try

import cdsapi
server = cdsapi.Client()

and then try some retrieve

**Comment by Akhilauppala2056** [comment]
No I didn't get such messages. The error that I mentioned is coming again
and again. Finally it is getting terminated.

**Comment by amcz** [comment]
I suggest you try to run some of the simple examples from the cdsapi page first.
https://cds.climate.copernicus.eu/api-how-to

scroll to the end and try the example they give there.

**Comment by Akhilauppala2056** [comment]
Thank you so much. My problem is solved. Now I can run it without any
errors.

**Comment by Akhilauppala2056** [comment]
Now i am facing a new problem.During conversion from era5 file format to
arl format, I am giving correct path of era52arl.f file but it is showing
the following error
/home/akhi/Desktop/era52arl/era52arl
-i/home/akhi/Desktop/hysplit_metdata-master/ERA5_.Jan{01}.3dplgrib
-a/home/akhi/Desktop/hysplit_metdata-master/ERA5_.Jan{01}.2dpl.all.grib
./example_small_area.sh: line 18: /home/akhi/Desktop/era52arl/era52arl: No
such file or directory
mv: cannot stat 'DATA.ARL': No such file or directory
From the following lines you can era52arl.f file path
akhi@akhiuppala:~/Desktop/era52arl$ ls
era52arl.f  Makefile  Readme_era52arl.txt

Please help me to get out of this problem.
