### ISSUE TITLE
conversion of era5 data to ARL format

### ISSUE THREAD

**Issue by Akhilauppala2056** [amcz/hysplit_metdata#8]
In shell script If i am not giving file name as era52arl.f error is coming like file is not in the specified directory. when i am giving it as era52arl.f  it is accessing that file but it is not converting grib files into arl format. It is saying each and every line in that fortran file as an error.

**Comment by amcz** [comment]
Have you compiled era52arl? You need to compile it and make sure the executable is available in the directory.

**Comment by Akhilauppala2056** [comment]
Below attachment shows errors that i am getting

**Comment by amcz** [comment]
This comment has to do with the fortran program era52arl.f and not the python code.
